### ISSUE TITLE
add https binding not working

### ISSUE THREAD

**Issue by mmikkelson** [Microsoft/vsts-rm-extensions#140]
**Task configuration follows...**
```
Create or Update Website: true
Website Name: $(siteName)
Physical Path: $(physicalPath)
Physical Path Authentication: Application User (Pass-through)
Add Binding: true
Protocol: https
IP Address: $(ipAddress)
SNI: false
Host Name: $(hostname)
SSL Certificate Thumbprint: $(sslCertificateThumbprint)

```
New binding is created, no certificate selected:

**Edit Site Binding dialog**:
```
Type: https
IP Address: correct IP passed from task
Port: 443
Host name: correct host name passed from task
SSL Certificate: Not Selected
```
When I click the drown-down, i'm able to select the correct certificate, the add binding option does not take care of this.

**Comment by KrishnaAdityaB** [comment]
@mmikkelson 
It seems like parsing issue with PowerShell as mentioned [here](http://stackoverflow.com/questions/9722273/using-netsh-on-powershell-fails-with-error-the-parameter-is-incorrect).

Can you correct this in the task file from you agent's folder and try the Build/Release again? https://github.com/Microsoft/vsts-rm-extensions/blob/master/Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppMgmt/AppCmdOnTargetMachines.ps1#L207

If the above fix works for you - Please share your environment details for reproduction.
OS Version, PS Version, Agent run as service/process.

**Comment by KrishnaAdityaB** [comment]
@mmikkelson 
In some cases we noticed that Copying the certificate thumb print from Certificate Manager copies an invisible character - This causes "The parameter is incorrect." error. 
Please carefully select the thumbprint without that character. You can verify this by pasting the copied value in a notepad. Saving it will raise a pop-up saying "this file contains characters in Unicode format".

**Comment by KrishnaAdityaB** [comment]
@mmikkelson I formatted the issue description according to my interpretation. 

Can you share me the debug logs of the task?
Set a build/release variable with name _System.Debug_ and value _true_. Run the scenario and share the logs here or mail them to RM_Customer_Queries at microsoft dot com

**Comment by mmikkelson** [comment]
...
76 2016-11-22T17:01:52.9175743Z Checking if SslCert binding is already present. Running command : netsh http show sslcert ipport=0.0.0.0:443
77 2016-11-22T17:01:52.9175743Z Setting SslCert for website.
78 2016-11-22T17:01:52.9185796Z Not enabling SNI : sni : false, iisVersion : 8, hostname : wwwdev.extdev.wellmark.com. Possible Reasons: 
79 2016-11-22T17:01:52.9195869Z  1. IIS Version is less than 8 
80 2016-11-22T17:01:52.9195869Z  2. HostName input is not provided 
81 2016-11-22T17:01:52.9205736Z  3. SNI input is set to false
82 2016-11-22T17:01:52.9215738Z Exiting Execute-Main function
83 2016-11-22T17:01:52.9215738Z SITE object "website" changed
84 2016-11-22T17:01:52.9225787Z The syntax supplied for this command is not valid. Check help for the correct syntax.
85 2016-11-22T17:01:52.9225787Z  
86 2016-11-22T17:01:52.9235811Z Usage: add sslcert hostnameport=<name:port> | ipport=<ipaddr:port> | ccs=<port>  
87 2016-11-22T17:01:52.9245746Z 	appid=<GUID> 
88 2016-11-22T17:01:52.9245746Z 	[certhash=<string>]
89 2016-11-22T17:01:52.9255747Z 	[certstorename=<string>]
90 2016-11-22T17:01:52.9265815Z 	[verifyclientcertrevocation=enable|disable]
...

**Comment by mmikkelson** [comment]
determined that the task fails if the parameter for the thumbprint does not include whitespace, but the netsh command expects the thumbprint to have the whitespace removed. possible bug in the powershell script?

AppCmdOnTargetMachines.ps1 - made following changes for troubleshooting on my agent machine
 
added the following after line 196
    #trim whitespace from certhash parm
    $certhash = $certhash.Replace(" ","")

added Write-Verbose $addCertCmd after line 230

netsh command requires the appid guid to be wrapped in single quotes, which the script is not doing. 
modify line 209 ... appid=`'{{{3}}}`' ...
modify line 219 ... appid=`'{{{2}}}`' ...
this will properly format the appid parm for the netsh command, but the task fails with parameter incorrect error message. 

output of Write-Verbose above is as follows:
netsh http add sslcert ipport=0.0.0.0:443 certhash=‎‎‎‎‎efdf4edc97f6f75930685dcc8821be1fe9472c4c appid='{d9f79eda-d1d1-431c-a24e-1c66fcffd48f}'
if this command is executed manually, the binding creation is successful

**Comment by KrishnaAdityaB** [comment]
@mvvsubbu can you provide context on why cerstoreName param is passed in line 207 but not 217?
@mmikkelson can you raise a PR with your changes - so that it will let us understand the gap for your scenario? Thanks

**Comment by mvvsubbu** [comment]
if we have not passed certstorename option, default value is MY https://msdn.microsoft.com/en-us/library/windows/desktop/cc307220(v=vs.85).aspx

**Comment by stas-sultanov** [comment]
Hi, there, 
I'm facing exact the same issue.
certificates is not selected after the task completes.

**Comment by mmikkelson** [comment]
@mvvsubbu I understand that the expected behavior for `netsh http add sslcert` without the certstorename parameter *should* default to "MY", however, observed behavior when executing the following command does not support that expectation, hence the raised issue.
`netsh http add sslcert ipport=0.0.0.0:443 certhash=5226dc6c54559761cd471b86eb51c096252c90f2 appid='{4dc3e181-e14b-4a21-b022-59fc669b0914}'`
after running this command, the output of `netsh http show sslcert ipport=0.0.0.0:443` results in the following:

    SSL Certificate bindings:
    -------------------------
    IP:port                      : 0.0.0.0:443
    Certificate Hash             : 5226dc6c54559761cd471b86eb51c096252c90f2
    Application ID               : {4dc3e181-e14b-4a21-b022-59fc669b0914}
    Certificate Store Name       : (null)
    Verify Client Certificate Revocation : Enabled
    Verify Revocation Using Cached Client Certificate Only : Disabled
    Usage Check                  : Enabled
    Revocation Freshness Time    : 0
    URL Retrieval Timeout        : 0
    Ctl Identifier               : (null)
    Ctl Store Name               : (null)
    DS Mapper Usage              : Disabled
    Negotiate Client Certificate : Disabled

please note the value of `(null)` for Certificate Store Name

**Comment by mvvsubbu** [comment]
Closing the issue as fix is released

**Comment by duaneking** [comment]
This is still an issue, we cant see or edit our iis bindings in the azure devops UI.
